#Minecraft server properties
#Mon Feb 09 00:54:53 CET 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=easy
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,fabric,academy,accessories,advancementframes,another_furniture,arts_and_crafts,atistructures,balm,beautify,biomeswevegone,bookshelf,chalk,cobbledgacha,cobblefurnies,cobbleloots,cobblemon,cobblemon_simple_center,cobblemonalphas,cobblemonraiddens,cobblemontrialsedition,cobblenav,cobbreeding,collective,comforts,connectiblechains,constructionwand,cozyhome,craftingtweaks,darkutils,dye_depot,dynamiccrosshair-api,dynamiccrosshaircompat,easy_npc,easy_npc_config_ui,elevatorid,emojiful,enhancedcelestials,exposure,exposure_expanded,exposure_polaroid,fabric-convention-tags-v2,farmers_structures,farmersdelight,fireworkcapsules,fwaystones,glassential,handcrafted,hopobetterunderwaterruins,knowlogy,laserbridges,letsparkour,libraryferret,lootr,mega_showdown,mes,mns,moonlight,mr_farmers_cuttingohthebiomeswevegone,mr_farmers_cuttingregionsunexplored,mss,mtr,mvs,naturescompass,nyctography,ohthetreesyoullgrow,pigpen,player_roles,porting_lib_item_abilities,rad-gyms,rctmod,rechiseled,regions_unexplored,runelic,scholar,shutter,simpletms,sootychimneys,sophisticatedcore,sophisticatedstorage,stohuns_vanity_collection,stoneworks,supermartijn642corelib,templates,terrablender,tim_core,toms_storage,totw_modded,treechop,trinkets,vanity,visualworkbench,wwoo,xercapaint,yungsapi,zamega
level-name=world
level-seed=
level-type=default
log-ips=true
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=10
max-tick-time=-1
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=26166
rate-limit=0
rcon.password=BF0729QhbXrGAH6M
rcon.port=26167
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=109.239.156.196
server-port=26165
simulation-distance=10
snooper-enabled=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
